Issue 455
BoldGrid/boldgrid-backup pull request #459
Opened 2021-03-30 16:21 UTC by bwmarkle

2021-04-08 13:43 UTC, jamesros161 approved these changes

2021-04-08 17:38 UTC, cssjoe requested changes
Optimize the new commands.

2021-04-08 17:38 UTC, cssjoe commented on bin/release.sh
> +find vendor/. -name ".git" -type d -exec rm -rf {} +
Combine the commands; use this:
```
find vendor/ -name ".git" -type d -print -exec rm -rf {} +
```

2021-04-13 17:49 UTC, bwmarkle commented on bin/release.sh
> +find vendor/. -name ".git" -type d -exec rm -rf {} +
done.

2021-04-13 17:50 UTC, cssjoe approved these changes

2021-04-13 18:03 UTC, merged