Pdo socket
BoldGrid/boldgrid-backup pull request #529
Opened 2022-07-25 16:47 UTC by joe9663

2022-07-29 18:26 UTC, bwmarkle requested changes

2022-07-29 18:26 UTC, bwmarkle commented on admin/class-boldgrid-backup-admin-db-dump.php
> +        if ( 'sock' === pathinfo( $db_host[0], PATHINFO_EXTENSION ) || 'sock' === pathinfo( $db_host[1], PATHINFO_EXTENSION ) ) {
Instead of custom logic, could we use https://developer.wordpress.org/reference/classes/wpdb/parse_db_host/ ?

2022-07-29 18:26 UTC, bwmarkle commented on admin/class-boldgrid-backup-admin-db-import.php
> +        // Parameters to check the DB_HOST setup
It looks like we may be duplicating code?

Is it possible simply call `get_connection_string()`?

2026-08-03 16:05 UTC, cssjoe commented
Closing as superseded / stale: socket-aware DB host handling is already present on `master` (from earlier socket/port work). This branch has long-standing merge conflicts and requested changes, and a clean follow-up would need a fresh PR if we still want to switch to `wpdb::parse_db_host()`.

2026-08-03 16:05 UTC, closed without merging