update phpseclib/phpseclib
BoldGrid/boldgrid-backup pull request #579
Opened 2023-12-29 18:49 UTC by SitesByYogi

phpseclib/phpseclib library to version ~3.0

2024-01-03 15:16 UTC, jamesros161 approved these changes

2024-04-23 19:31 UTC, cssjoe requested changes
If we're keeping PHP 5.6 support, then find the latest version that has the deprecated error fix and still supports PHP 5.6 and up.
I don't see what version dropped PHP 5 support.  3.0.13 (2022-01-30) has a fix for PHP 5.6, so I guess that works for PHP 5.6 but needs testing.
Basically, we can use the latest version that supports PHP 5.6 and hope that it fixes that error.  It may be 3.0.22.

2024-04-24 17:17 UTC, W3ap0n-X commented
Was able to test on php 5.6 with phpseclib version 3.0.37 with no issues setting up ftp connection/db encryption and taking a backup.

2026-08-03 16:05 UTC, cssjoe commented
Closing as superseded: `phpseclib/phpseclib` is already on `~3.0` in `composer.json` / `composer.lock` on `master`. This PR also has merge conflicts and prior change requests.

2026-08-03 16:05 UTC, closed without merging